
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CampsiteAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7048, 1, -2, 0}, {7044, 1, -1, 0}, {4965, 0, 0, 0}// 1	2	3	
			, {4966, 0, -4, 0}, {4967, 1, -4, 0}, {4973, 1, 0, 0}// 4	5	6	
			, {6003, 0, -3, 0}, {6007, 0, -2, 0}, {4972, 0, -1, 0}// 7	8	9	
			, {2529, 0, -1, 2}, {496, -2, 3, 0}, {497, -3, 3, 0}// 10	11	12	
			, {497, -4, 3, 0}, {497, -5, 3, 0}, {498, -2, 2, 0}// 13	14	15	
			, {498, -2, 0, 0}, {500, -6, 3, 0}, {501, -2, -1, 0}// 16	17	18	
			, {505, -3, -1, 0}, {505, -4, -1, 0}, {505, -5, -1, 0}// 19	20	21	
			, {504, -6, 1, 0}, {504, -6, 2, 0}, {504, -6, 0, 0}// 22	23	24	
			, {499, -6, -1, 0}, {1540, -1, 4, 31}, {1541, -1, 1, 31}// 25	26	27	
			, {1536, -2, 1, 31}, {1536, -3, 1, 31}, {1537, -2, 4, 31}// 28	29	30	
			, {1537, -3, 4, 31}, {1535, -4, 3, 31}, {1535, -4, 2, 31}// 31	32	33	
			, {1538, -1, 2, 31}, {1538, -1, 3, 31}, {1540, -2, 3, 34}// 34	35	36	
			, {1541, -2, 2, 34}, {1542, -4, 1, 31}, {1542, -3, 2, 34}// 37	38	39	
			, {1543, -4, 4, 31}, {1543, -3, 3, 34}, {2645, -4, 0, 0}// 40	41	42	
			, {2906, -1, 0, 0}, {2906, -1, 2, 0}, {2876, -1, 3, 0}// 43	44	45	
			, {4587, -5, 0, 5}, {4007, -1, 3, 6}, {7049, 2, -2, 0}// 46	47	48	
			, {7050, 3, -2, 0}, {7052, 3, -1, 0}, {7043, 2, -1, 0}// 49	50	51	
			, {7050, 3, -3, 0}, {7067, 3, -2, 0}, {4964, 4, 0, 0}// 54	55	56	
			, {4968, 3, 0, 0}, {4969, 4, -1, 0}, {4970, 2, -4, 0}// 57	58	59	
			, {4971, 3, -4, 0}, {4972, 2, 0, 0}, {6004, 4, -4, 0}// 60	61	62	
			, {6011, 4, -3, 0}, {4972, 4, -2, 0}, {2431, 2, -4, 2}// 63	64	65	
			, {2528, 4, 0, 3}, {7831, 6, 1, 2}, {7833, 6, 2, 2}// 66	68	69	
			, {4585, 3, 2, 0}, {4584, 2, 2, 0}, {4583, 6, -2, 0}// 70	71	72	
			, {4582, 6, -3, 0}, {3608, 3, 2, 1}, {3606, 6, -2, 1}// 73	74	75	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CampsiteAddonDeed();
			}
		}

		[ Constructable ]
		public CampsiteAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 14732, 2, -1, 0, 0, 10, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 14742, 3, -2, 1, 0, 10, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 4012, 6, 1, 0, 0, 10, "", 1);// 67

		}

		public CampsiteAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CampsiteAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CampsiteAddon();
			}
		}

		[Constructable]
		public CampsiteAddonDeed()
		{
			Name = "Campsite";
		}

		public CampsiteAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}