
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ClothBedNSNoPillowsAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {5990, -1, -1, 0}, {5990, -1, 0, 0}, {5990, -1, 1, 0}// 1	2	3	
			, {5990, 0, -1, 0}, {5990, 0, 0, 0}, {5990, 0, 1, 0}// 4	5	6	
			, {5990, 1, -1, 0}, {5990, 1, 0, 0}, {5990, 1, 1, 0}// 7	8	9	
			, {5990, -1, -1, 1}, {5990, -1, 0, 1}, {5990, -1, 1, 1}// 10	11	12	
			, {5990, 0, -1, 1}, {5990, 0, 0, 1}, {5990, 0, 1, 1}// 13	14	15	
			, {5990, 1, -1, 1}, {5990, 1, 0, 1}, {5990, 1, 1, 1}// 16	17	18	
			, {5990, -1, -1, 2}, {5990, -1, 0, 2}, {5990, -1, 1, 2}// 19	20	21	
			, {5990, 0, -1, 2}, {5990, 0, 0, 2}, {5990, 0, 1, 2}// 22	23	24	
			, {5990, 1, -1, 2}, {5990, 1, 0, 2}, {5990, 1, 1, 2}// 25	26	27	
			, {5990, -1, -1, 3}, {5990, -1, 0, 3}, {5990, -1, 1, 3}// 28	29	30	
			, {5990, 0, -1, 3}, {5990, 0, 0, 3}, {5990, 0, 1, 3}// 31	32	33	
			, {5990, 1, -1, 3}, {5990, 1, 0, 3}, {5990, 1, 1, 3}// 34	35	36	
			, {5990, -1, -1, 4}, {5990, -1, 0, 4}, {5990, -1, 1, 4}// 37	38	39	
			, {5990, 0, -1, 4}, {5990, 0, 0, 4}, {5990, 0, 1, 4}// 40	41	42	
			, {5990, 1, -1, 4}, {5990, 1, 0, 4}, {5990, 1, 1, 4}// 43	44	45	
			, {3530, -1, 0, 5}, {3530, -1, 1, 5}, {3530, 0, 0, 5}// 46	47	48	
			, {3530, 0, 1, 5}, {3530, 1, 0, 5}, {3530, 1, 1, 5}// 49	50	51	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ClothBedNSNoPillowsAddonDeed();
			}
		}

		[ Constructable ]
		public ClothBedNSNoPillowsAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public ClothBedNSNoPillowsAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ClothBedNSNoPillowsAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ClothBedNSNoPillowsAddon();
			}
		}

		[Constructable]
		public ClothBedNSNoPillowsAddonDeed()
		{
			Name = "ClothBedNSNoPillows";
		}

		public ClothBedNSNoPillowsAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}