
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class countrykitchenAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7979, 0, -3, 6}, {7979, 1, -3, 6}, {4161, -1, -3, 6}// 12	13	35	
			, {4159, 2, -3, 6}, {5634, -3, 1, 7}, {1801, 0, 0, 0}// 36	38	39	
			, {5924, 0, 1, 10}, {2530, 2, -2, 18}, {7711, 1, 0, 6}// 43	48	49	
			, {2477, -2, 1, 15}, {2547, 1, -2, 18}, {5375, -3, -2, 7}// 50	51	52	
			, {2450, 1, 1, 6}, {2430, 1, 1, 7}, {2521, 1, 1, 16}// 53	54	55	
			, {2444, -2, -3, 6}, {4163, -3, -1, 7}, {2519, 1, 2, 16}// 56	57	59	
			, {2519, 1, 2, 17}, {2519, 1, 2, 18}, {3706, -3, -3, 17}// 60	61	62	
			, {5625, 4, -1, 5}, {2451, 4, 0, 5}, {2540, 4, -2, 14}// 79	80	81	
			, {5643, 4, 0, 14}, {6274, 4, -3, 15}, {4156, 4, 1, 14}// 83	84	85	
			, {3129, 4, 3, 0}, {3136, 4, 3, 0}, {3134, 4, 3, 0}// 86	87	88	
			, {1801, 4, -2, 0}, {1801, 4, 1, 0}, {1801, 4, 0, 0}// 89	90	91	
			, {1801, 4, -1, 0}, {5921, 4, -2, 5}, {4323, 4, 1, 5}// 92	97	98	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new countrykitchenAddonDeed();
			}
		}

		[ Constructable ]
		public countrykitchenAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 4610, -3, -2, 1, 2785, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 4609, -3, -1, 1, 2785, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 4613, -2, -3, 0, 2785, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 4612, -1, -3, 0, 2785, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 4613, 2, -3, 0, 2785, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1801, 0, -3, 1, 2785, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1801, 1, -3, 1, 2785, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1801, -3, -3, 10, 2624, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 4612, 3, -3, 0, 2785, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1801, -3, -3, 0, 2624, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1801, -3, -3, 5, 2624, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 272, -2, 2, 11, 2779, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 272, -2, -1, 11, 2779, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 272, -2, 0, 11, 2779, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 272, -2, 1, 11, 2779, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 271, -1, -2, 10, 2779, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 271, 0, -2, 10, 2779, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 271, 3, -2, 10, 2779, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1105, 1, -2, 12, 1, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1105, 2, -2, 12, 1, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 10332, -3, -1, 10, 2779, -1, "Cabinet", 1);// 23
			AddComplexComponent( (BaseAddon) this, 10332, -3, 1, 10, 2779, -1, "Cabinet", 1);// 24
			AddComplexComponent( (BaseAddon) this, 10332, -3, -2, 10, 2779, -1, "Cabinet", 1);// 25
			AddComplexComponent( (BaseAddon) this, 10331, -1, -3, 10, 2779, -1, "Cabinet", 1);// 26
			AddComplexComponent( (BaseAddon) this, 10331, -2, -3, 10, 2779, -1, "Cabinet", 1);// 27
			AddComplexComponent( (BaseAddon) this, 10331, 2, -3, 11, 2779, -1, "Cabinet", 1);// 28
			AddComplexComponent( (BaseAddon) this, 10331, 3, -3, 11, 2779, -1, "Cabinet", 1);// 29
			AddComplexComponent( (BaseAddon) this, 4610, -3, -1, 1, 2785, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 4611, -3, 0, 1, 2785, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 4609, -3, 1, 1, 2785, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 3704, -3, 0, 9, 0, -1, "Sink", 1);// 33
			AddComplexComponent( (BaseAddon) this, 268, -4, 0, 5, 2779, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 5622, -1, 1, 14, 82, -1, "Towel", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1801, 0, 1, 0, 2624, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1801, 1, 0, 0, 2624, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1801, 1, 1, 0, 2624, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1297, 0, 0, 6, 2779, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1297, 0, 1, 6, 2779, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 1297, 1, 0, 6, 2779, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1297, 1, 1, 6, 2779, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 11526, -2, 3, 11, 2785, -1, "Fridgerator", 1);// 58
			AddComplexComponent( (BaseAddon) this, 4100, -3, 0, 14, 2785, -1, "Faucet", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1801, 4, -3, 0, 2624, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1801, 4, -3, 5, 2624, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1801, 4, -3, 10, 2624, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1801, 4, 2, 0, 2624, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 1801, 4, 2, 5, 2624, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1801, 4, 2, 10, 2624, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 2886, 4, 2, 15, 2283, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 272, 4, 0, 0, 2779, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 272, 4, 1, 0, 2779, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 272, 4, -1, 0, 2779, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 272, 4, -2, 0, 2779, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 1998, 4, -2, 13, 2785, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 1998, 4, -1, 13, 2785, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 1998, 4, 0, 13, 2785, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 1998, 4, 1, 13, 2785, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 4158, 4, -1, 14, 2785, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1997, 4, -2, 4, 2785, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1997, 4, -1, 4, 2785, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1997, 4, 0, 4, 2785, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 1997, 4, 1, 4, 2785, -1, "", 1);// 96

		}

		public countrykitchenAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class countrykitchenAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new countrykitchenAddon();
			}
		}

		[Constructable]
		public countrykitchenAddonDeed()
		{
			Name = "countrykitchen";
		}

		public countrykitchenAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}