
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GazeboAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {10721, -1, -2, 25}, {10721, -1, -1, 25}, {10721, -1, 0, 25}// 105	106	107	
			, {10721, -1, 1, 25}, {10721, -1, 2, 25}, {10721, 2, -3, 25}// 108	109	134	
			, {10721, 2, -2, 25}, {10721, 2, -1, 25}, {10721, 2, 0, 25}// 135	136	137	
			, {10721, 2, 1, 25}, {10721, 2, 2, 25}, {10721, -4, 2, 25}// 138	139	159	
			, {3215, -1, 6, 0}, {3215, 0, 6, 0}, {3215, 1, 6, 0}// 209	210	211	
			, {3215, 2, 6, 0}, {3215, 3, 6, 0}, {3215, -2, 6, 0}// 212	213	214	
			, {3215, -2, -5, 0}, {3215, -1, -5, 0}, {3215, 0, -5, 0}// 215	216	217	
			, {3215, 1, -5, 0}, {3215, 2, -5, 0}, {3215, 3, -5, 0}// 218	219	220	
			, {3215, -5, -2, 0}, {3215, -5, -1, 0}, {3215, -5, 0, 0}// 221	222	223	
			, {3215, -5, 1, 0}, {3215, -5, 2, 0}, {3215, -5, 3, 0}// 224	225	226	
			, {11516, -1, 6, 7}, {11516, 0, 6, 7}, {11516, 1, 6, 7}// 227	228	229	
			, {11516, 2, 6, 7}, {11516, -1, -4, 5}, {11516, 0, -4, 5}// 230	231	232	
			, {11516, 1, -4, 5}, {11516, 2, -4, 5}, {11514, -4, -1, 5}// 233	234	235	
			, {11514, -4, 0, 5}, {11514, -4, 1, 5}, {11514, -4, 2, 5}// 236	237	238	
			, {3215, 6, -2, 0}, {3215, 6, -1, 0}, {3215, 6, 0, 0}// 279	280	281	
			, {3215, 6, 1, 0}, {3215, 6, 2, 0}, {3215, 6, 3, 0}// 282	283	284	
			, {11514, 6, -1, 7}, {11514, 6, 0, 7}, {11514, 6, 1, 7}// 285	286	287	
			, {11514, 6, 2, 7}// 288	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GazeboAddonDeed();
			}
		}

		[ Constructable ]
		public GazeboAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1179, -4, 0, 5, 1153, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1179, -4, 1, 5, 1153, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1179, -4, 2, 5, 1153, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1179, -3, 0, 5, 1153, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1179, -3, 1, 5, 1153, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1179, -3, 2, 5, 1153, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1179, -3, 3, 5, 1153, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1179, -2, 0, 5, 1153, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1179, -2, 1, 5, 1153, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1179, -2, 2, 5, 1153, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1179, -2, 3, 5, 1153, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1179, -2, 4, 5, 1153, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1179, -1, 0, 5, 1153, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1179, -1, 1, 5, 1153, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1179, -1, 2, 5, 1153, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1179, -1, 3, 5, 1153, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1179, -1, 4, 5, 1153, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1179, -1, 5, 5, 1153, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1179, 0, 0, 5, 1153, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1179, 0, 1, 5, 1153, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1179, 0, 2, 5, 1153, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1179, 0, 3, 5, 1153, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1179, 0, 4, 5, 1153, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1179, 0, 5, 5, 1153, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 1179, 1, 0, 5, 1153, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 1179, 1, 1, 5, 1153, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 1179, 1, 2, 5, 1153, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1179, 1, 3, 5, 1153, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1179, 1, 4, 5, 1153, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1179, 1, 5, 5, 1153, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1179, -4, -1, 5, 1153, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1179, -3, -1, 5, 1153, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1179, -2, -1, 5, 1153, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1179, -1, -1, 5, 1153, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1179, 0, -1, 5, 1153, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1179, 1, -1, 5, 1153, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1179, 2, -1, 5, 1153, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1179, 2, 0, 5, 1153, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1179, 2, 1, 5, 1153, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1179, 2, 2, 5, 1153, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1179, 2, 3, 5, 1153, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1179, 2, 4, 5, 1153, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1179, 2, 5, 5, 1153, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1179, -3, -2, 5, 1153, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1179, -2, -3, 5, 1153, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 1179, -2, -2, 5, 1153, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1179, -1, -4, 5, 1153, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 1179, -1, -3, 5, 1153, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 1179, -1, -2, 5, 1153, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 1179, 0, -4, 5, 1153, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 1179, 0, -3, 5, 1153, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1179, 0, -2, 5, 1153, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1179, 1, -4, 5, 1153, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1179, 1, -3, 5, 1153, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1179, 1, -2, 5, 1153, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1179, 2, -4, 5, 1153, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1179, 2, -3, 5, 1153, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1179, 2, -2, 5, 1153, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1179, 3, -3, 5, 1153, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1179, 3, -2, 5, 1153, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1179, 3, -1, 5, 1153, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1179, 3, 0, 5, 1153, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1179, 3, 1, 5, 1153, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1179, 3, 2, 5, 1153, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1179, 3, 3, 5, 1153, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1179, 3, 4, 5, 1153, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1819, 3, 5, 0, 961, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 1818, -4, -2, 0, 961, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1818, -3, -3, 0, 961, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1818, -2, -4, 0, 961, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1820, 3, -4, 0, 961, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1821, -4, 3, 0, 961, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1821, -3, 4, 0, 961, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1821, -2, 5, 0, 961, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 1812, -4, 4, 0, 961, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 1812, -3, 5, 0, 961, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 1810, -4, -3, 0, 961, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 1810, -3, -4, 0, 961, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 280, 2, 5, 0, 961, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 280, 1, 5, 0, 961, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 280, 0, 5, 0, 961, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 280, -1, 5, 0, 961, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 280, -1, -5, 0, 1150, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 280, 0, -5, 0, 1150, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 280, 1, -5, 0, 1150, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 280, 2, -5, 0, 961, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 281, -5, -1, 0, 1150, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 281, -5, 0, 0, 1150, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 281, -5, 1, 0, 1150, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 281, -5, 2, 0, 961, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 10079, -5, -1, 5, 1153, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 10079, -5, 0, 5, 1153, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 10079, -5, 1, 5, 1153, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 10079, -5, 2, 5, 1153, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 10082, -1, 5, 5, 1153, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 10082, 0, 5, 5, 1153, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 10082, 1, 5, 5, 1153, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 10082, 2, 5, 5, 1153, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 10082, -1, -5, 5, 1153, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 10082, 0, -5, 5, 1153, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 10082, 1, -5, 5, 1153, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 10082, 2, -5, 5, 1153, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 10721, -1, -4, 25, 1153, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 10721, -1, -3, 25, 1153, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 10721, -1, 3, 25, 1153, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 10721, -1, 4, 25, 1153, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 10721, -1, 5, 25, 1153, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 10721, 0, -4, 25, 1153, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 10721, 0, -3, 25, 1153, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 10721, 0, -2, 25, 1153, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 10721, 0, -1, 25, 1153, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 10721, 0, 0, 25, 1153, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 10721, 0, 1, 25, 1153, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 10721, 0, 2, 25, 1153, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 10721, 0, 3, 25, 1153, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 10721, 0, 4, 25, 1153, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 10721, 0, 5, 25, 1153, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 10721, 1, -4, 25, 1153, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 10721, 1, -3, 25, 1153, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 10721, 1, -2, 25, 1153, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 10721, 1, -1, 25, 1153, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 10721, 1, 0, 25, 1153, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 10721, 1, 1, 25, 1153, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 10721, 1, 2, 25, 1153, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 10721, 1, 3, 25, 1153, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 10721, 1, 4, 25, 1153, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 10721, 1, 5, 25, 1153, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 10721, 2, -4, 25, 1153, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 10721, 2, 3, 25, 1153, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 10721, 2, 4, 25, 1153, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 10721, 2, 5, 25, 1153, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 10721, 2, -3, 25, 1153, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 10721, 2, -2, 25, 1153, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 10721, 2, -1, 25, 1153, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 10721, 2, 0, 25, 1153, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 10721, 2, 1, 25, 1153, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 10721, 2, 2, 25, 1153, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 10721, 3, -3, 25, 1153, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 10721, 3, -2, 25, 1153, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 10721, 3, -1, 25, 1153, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 10721, 3, 0, 25, 1153, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 10721, 3, 1, 25, 1153, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 10721, 3, 2, 25, 1153, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 10721, -2, -3, 25, 1153, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 10721, -4, -1, 25, 1153, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 10721, -4, 0, 25, 1153, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 10721, -4, 1, 25, 1153, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 10721, -3, -2, 25, 1153, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 10721, -3, -1, 25, 1153, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 10721, -3, 0, 25, 1153, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 10721, -3, 1, 25, 1153, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 10721, -3, 2, 25, 1153, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 10721, -2, -2, 25, 1153, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 10721, -2, -1, 25, 1153, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 10721, -2, 0, 25, 1153, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 10721, -2, 1, 25, 1153, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 10721, -2, 2, 25, 1153, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 10721, -1, -2, 25, 1153, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 10721, -1, -1, 25, 1153, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 10721, -1, 0, 25, 1153, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 10721, -1, 1, 25, 1153, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 10721, -1, 2, 25, 1153, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 10721, -4, 2, 25, 1153, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 10721, -3, 3, 25, 1153, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 10721, -2, 3, 25, 1153, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 10721, -2, 4, 25, 1153, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 10722, -1, -5, 25, 1153, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 10722, 0, -5, 25, 1153, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 10722, 1, -5, 25, 1153, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 10722, 2, -5, 25, 1153, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 10722, 3, -4, 25, 1153, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 10721, 3, 3, 25, 1153, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 10721, 3, 4, 25, 1153, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 10723, -5, -1, 25, 1153, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 10723, -5, 0, 25, 1153, -1, "", 1);// 187
			AddComplexComponent( (BaseAddon) this, 10723, -5, 1, 25, 1153, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 10723, -5, 2, 25, 1153, -1, "", 1);// 189
			AddComplexComponent( (BaseAddon) this, 10722, -4, -2, 25, 1153, -1, "", 1);// 190
			AddComplexComponent( (BaseAddon) this, 10723, -4, 3, 25, 1153, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 10723, -3, 4, 25, 1153, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 10723, -2, 5, 25, 1153, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 10723, -4, -2, 25, 1153, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 10723, -3, -3, 25, 1153, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 10723, -2, -4, 25, 1153, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 10724, -2, -5, 25, 1153, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 10724, -5, -2, 25, 1153, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 10722, -3, -3, 25, 1153, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 10722, -2, -4, 25, 1153, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 10724, -4, -3, 25, 1153, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 10724, -3, -4, 25, 1153, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 15871, 0, -3, 5, 961, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 15871, 1, -3, 5, 961, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 15871, 0, 4, 5, 961, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 15871, 1, 4, 5, 961, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 15872, -3, 0, 5, 961, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 15872, -3, 1, 5, 961, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 1179, 4, -2, 5, 1153, -1, "", 1);// 239
			AddComplexComponent( (BaseAddon) this, 1179, 4, -1, 5, 1153, -1, "", 1);// 240
			AddComplexComponent( (BaseAddon) this, 1179, 4, 0, 5, 1153, -1, "", 1);// 241
			AddComplexComponent( (BaseAddon) this, 1179, 4, 1, 5, 1153, -1, "", 1);// 242
			AddComplexComponent( (BaseAddon) this, 1179, 4, 2, 5, 1153, -1, "", 1);// 243
			AddComplexComponent( (BaseAddon) this, 1179, 4, 3, 5, 1153, -1, "", 1);// 244
			AddComplexComponent( (BaseAddon) this, 1179, 5, -1, 5, 1153, -1, "", 1);// 245
			AddComplexComponent( (BaseAddon) this, 1179, 5, 0, 5, 1153, -1, "", 1);// 246
			AddComplexComponent( (BaseAddon) this, 1179, 5, 1, 5, 1153, -1, "", 1);// 247
			AddComplexComponent( (BaseAddon) this, 1179, 5, 2, 5, 1153, -1, "", 1);// 248
			AddComplexComponent( (BaseAddon) this, 1811, 4, 5, 0, 961, -1, "", 1);// 249
			AddComplexComponent( (BaseAddon) this, 1811, 5, 4, 0, 961, -1, "", 1);// 250
			AddComplexComponent( (BaseAddon) this, 1819, 4, 4, 0, 961, -1, "", 1);// 251
			AddComplexComponent( (BaseAddon) this, 1819, 5, 3, 0, 961, -1, "", 1);// 252
			AddComplexComponent( (BaseAddon) this, 1820, 5, -2, 0, 961, -1, "", 1);// 253
			AddComplexComponent( (BaseAddon) this, 1820, 4, -3, 0, 961, -1, "", 1);// 254
			AddComplexComponent( (BaseAddon) this, 1813, 5, -3, 0, 961, -1, "", 1);// 255
			AddComplexComponent( (BaseAddon) this, 1813, 4, -4, 0, 961, -1, "", 1);// 256
			AddComplexComponent( (BaseAddon) this, 281, 5, -1, 0, 961, -1, "", 1);// 257
			AddComplexComponent( (BaseAddon) this, 281, 5, 0, 0, 961, -1, "", 1);// 258
			AddComplexComponent( (BaseAddon) this, 281, 5, 1, 0, 961, -1, "", 1);// 259
			AddComplexComponent( (BaseAddon) this, 281, 5, 2, 0, 961, -1, "", 1);// 260
			AddComplexComponent( (BaseAddon) this, 10079, 5, -1, 5, 1153, -1, "", 1);// 261
			AddComplexComponent( (BaseAddon) this, 10079, 5, 0, 5, 1153, -1, "", 1);// 262
			AddComplexComponent( (BaseAddon) this, 10079, 5, 1, 5, 1153, -1, "", 1);// 263
			AddComplexComponent( (BaseAddon) this, 10079, 5, 2, 5, 1153, -1, "", 1);// 264
			AddComplexComponent( (BaseAddon) this, 10721, 4, -2, 25, 1153, -1, "", 1);// 265
			AddComplexComponent( (BaseAddon) this, 10721, 4, -1, 25, 1153, -1, "", 1);// 266
			AddComplexComponent( (BaseAddon) this, 10721, 4, 0, 25, 1153, -1, "", 1);// 267
			AddComplexComponent( (BaseAddon) this, 10721, 4, 1, 25, 1153, -1, "", 1);// 268
			AddComplexComponent( (BaseAddon) this, 10721, 4, 2, 25, 1153, -1, "", 1);// 269
			AddComplexComponent( (BaseAddon) this, 10721, 5, -1, 25, 1153, -1, "", 1);// 270
			AddComplexComponent( (BaseAddon) this, 10721, 5, 0, 25, 1153, -1, "", 1);// 271
			AddComplexComponent( (BaseAddon) this, 10721, 5, 1, 25, 1153, -1, "", 1);// 272
			AddComplexComponent( (BaseAddon) this, 10721, 5, 2, 25, 1153, -1, "", 1);// 273
			AddComplexComponent( (BaseAddon) this, 10722, 5, -2, 25, 1153, -1, "", 1);// 274
			AddComplexComponent( (BaseAddon) this, 10722, 4, -3, 25, 1153, -1, "", 1);// 275
			AddComplexComponent( (BaseAddon) this, 10721, 4, 3, 25, 1153, -1, "", 1);// 276
			AddComplexComponent( (BaseAddon) this, 15872, 4, 0, 5, 961, -1, "", 1);// 277
			AddComplexComponent( (BaseAddon) this, 15872, 4, 1, 5, 961, -1, "", 1);// 278

		}

		public GazeboAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GazeboAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GazeboAddon();
			}
		}

		[Constructable]
		public GazeboAddonDeed()
		{
			Name = "Gazebo";
		}

		public GazeboAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}