
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GreenhouseEmptyAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1824, -4, -4, 0}, {1824, -4, -3, 0}, {1824, -4, -2, 0}// 1	2	3	
			, {1824, -4, -1, 0}, {1824, -4, 0, 0}, {1824, -4, 1, 0}// 4	5	6	
			, {1824, -4, 2, 0}, {1824, -4, 3, 0}, {1824, -3, -4, 0}// 7	8	9	
			, {1824, -3, -3, 0}, {1824, -3, -2, 0}, {1824, -3, -1, 0}// 10	11	12	
			, {1824, -3, 0, 0}, {1824, -3, 1, 0}, {1824, -3, 2, 0}// 13	14	15	
			, {1824, -3, 3, 0}, {1824, -2, -4, 0}, {1824, -2, -3, 0}// 16	17	18	
			, {1824, -2, -1, 0}, {1824, -2, 0, 0}, {1824, -2, 1, 0}// 19	20	21	
			, {1824, -2, 2, 0}, {1824, -2, 3, 0}, {1824, -1, -4, 0}// 22	23	24	
			, {1824, -1, -3, 0}, {1824, -1, -2, 0}, {1824, -1, -1, 0}// 25	26	27	
			, {1824, -1, 0, 0}, {1824, -1, 1, 0}, {1824, -1, 2, 0}// 28	29	30	
			, {1824, -1, 3, 0}, {1824, 0, -4, 0}, {1824, 0, -3, 0}// 31	32	33	
			, {1824, 0, -2, 0}, {1824, 0, -1, 0}, {1824, 0, 0, 0}// 34	35	36	
			, {1824, 0, 1, 0}, {1824, 0, 2, 0}, {1824, 0, 3, 0}// 37	38	39	
			, {1824, 1, -4, 0}, {1824, 1, -3, 0}, {1824, 1, -2, 0}// 40	41	42	
			, {1824, 1, -1, 0}, {1824, 1, 0, 0}, {1824, 1, 1, 0}// 43	44	45	
			, {1824, 1, 2, 0}, {1824, 1, 3, 0}, {1824, 2, -4, 0}// 46	47	48	
			, {1824, 2, -3, 0}, {1824, 2, -2, 0}, {1824, 2, -1, 0}// 49	50	51	
			, {1824, 2, 0, 0}, {1824, 2, 1, 0}, {1824, 2, 2, 0}// 52	53	54	
			, {1824, 3, -4, 0}, {1824, 3, -3, 0}, {1824, 3, -2, 0}// 55	56	57	
			, {1824, 3, -1, 0}, {1824, 3, 0, 0}, {1824, 3, 1, 0}// 58	59	60	
			, {1824, 3, 2, 0}, {1824, 4, -4, 0}, {1824, 4, -3, 0}// 61	62	63	
			, {1824, 4, -2, 0}, {1824, 4, -1, 0}, {1824, 4, 0, 0}// 64	65	66	
			, {1824, 4, 1, 0}, {1824, 4, 2, 0}, {1824, 2, 3, 0}// 67	68	69	
			, {1824, 3, 3, 0}, {1824, 4, 3, 0}, {1824, 5, -4, 0}// 70	71	72	
			, {1824, 5, -3, 0}, {1824, 5, -2, 0}, {1824, 5, -1, 0}// 73	74	75	
			, {1824, 5, 0, 0}, {1824, 5, 1, 0}, {1824, 5, 2, 0}// 76	77	78	
			, {1824, 5, 3, 0}, {13001, -1, -1, 5}, {13001, -1, 0, 5}// 79	134	135	
			, {13001, -1, 1, 5}, {13001, -1, 2, 5}, {13001, 0, -1, 5}// 136	137	138	
			, {13001, 0, 0, 5}, {13001, 0, 1, 5}, {13001, 0, 2, 5}// 139	140	141	
			, {13001, 1, -1, 5}, {13001, 1, 0, 5}, {13001, 1, 1, 5}// 142	143	144	
			, {13001, 1, 2, 5}, {13001, 2, -1, 5}, {13001, 2, 0, 5}// 145	146	147	
			, {13001, 2, 1, 5}, {13001, 2, 2, 5}, {9913, -4, -4, 14}// 148	149	155	
			, {9913, -4, -4, 9}, {4551, -3, -4, 12}, {4550, -4, -3, 17}// 156	157	158	
			, {4550, -4, -3, 11}, {2321, -4, 1, 11}, {2321, -4, -3, 11}// 159	160	161	
			, {2321, -1, -4, 11}, {2321, 1, -4, 11}, {2321, -3, -4, 11}// 162	163	164	
			, {2321, -4, -4, 11}, {1824, -2, -2, 0}, {1824, -4, 4, 0}// 165	166	267	
			, {1824, -4, 5, 0}, {1824, -3, 4, 0}, {1824, -3, 5, 0}// 268	269	270	
			, {1824, -2, 4, 0}, {1824, -2, 5, 0}, {1824, -1, 4, 0}// 271	272	273	
			, {1824, -1, 5, 0}, {1824, 0, 4, 0}, {1824, 0, 5, 0}// 274	275	276	
			, {1824, 1, 4, 0}, {1824, 1, 5, 0}, {1824, 2, 4, 0}// 277	278	279	
			, {1824, 2, 5, 0}, {1824, 3, 4, 0}, {1824, 3, 5, 0}// 280	281	282	
			, {1824, 4, 4, 0}, {1824, 4, 5, 0}, {1824, 5, 4, 0}// 283	284	285	
			, {1824, 5, 5, 0}, {1826, 0, 6, 0}, {1826, 1, 6, 0}// 286	287	288	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GreenhouseEmptyAddonDeed();
			}
		}

		[ Constructable ]
		public GreenhouseEmptyAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 10384, -5, -4, 5, 91, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 10384, -5, -3, 5, 91, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 10384, -5, -2, 5, 91, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 10384, -5, -1, 5, 91, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 10384, -5, 0, 5, 91, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 10384, -5, 1, 5, 91, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 10384, -5, 2, 5, 91, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 10384, -5, 3, 5, 91, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 10387, -4, -5, 5, 91, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 10387, -3, -5, 5, 91, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 10387, -2, -5, 5, 91, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 10387, -1, -5, 5, 91, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 10387, 0, -5, 5, 91, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 10387, 1, -5, 5, 91, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 10387, 2, -5, 5, 91, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 10387, 3, -5, 5, 91, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 10387, 4, -5, 5, 91, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 10387, 5, -5, 5, 91, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 10384, 5, -4, 5, 91, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 10384, 5, -3, 5, 91, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 10384, 5, -2, 5, 91, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 10384, 5, -1, 5, 91, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 10384, 5, 0, 5, 91, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 10384, 5, 1, 5, 91, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 10384, 5, 2, 5, 91, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 10384, 5, 3, 5, 91, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 7619, -4, -4, 5, 281, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 7619, -4, -3, 5, 281, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 7619, -4, -2, 5, 281, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 7619, -4, -1, 5, 281, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 7619, -4, 1, 5, 281, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 7620, 2, -4, 5, 281, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 7622, -3, -4, 5, 281, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 7622, -2, -4, 5, 281, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 7622, -1, -4, 5, 281, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 7622, 0, -4, 5, 281, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 7622, 1, -4, 5, 281, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 7617, -4, 2, 5, 281, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 279, 2, 2, 5, 91, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 280, -1, 2, 5, 91, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 280, 0, 2, 5, 91, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 280, 1, 2, 5, 91, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 281, 2, 1, 5, 91, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 281, 2, -1, 5, 91, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 281, 2, 0, 5, 91, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 280, -1, -2, 5, 91, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 280, 0, -2, 5, 91, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 280, 1, -2, 5, 91, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 280, 2, -2, 5, 91, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 281, -2, 2, 5, 91, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 281, -2, -1, 5, 91, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 281, -2, 0, 5, 91, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 281, -2, 1, 5, 91, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 282, -2, -2, 5, 91, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 4153, -3, -3, 5, 0, -1, "Potting Soil", 1);// 150
			AddComplexComponent( (BaseAddon) this, 4153, -3, -3, 7, 0, -1, "Potting Soil", 1);// 151
			AddComplexComponent( (BaseAddon) this, 4153, -3, -3, 9, 0, -1, "Potting Soil", 1);// 152
			AddComplexComponent( (BaseAddon) this, 4024, -3, -3, 11, 2997, -1, "Gardening Trowel", 1);// 153
			AddComplexComponent( (BaseAddon) this, 10403, -5, -5, 5, 91, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 7619, -4, 0, 5, 281, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1535, -5, -5, 17, 91, -1, "Greenhouse Roof", 1);// 168
			AddComplexComponent( (BaseAddon) this, 1535, -5, -3, 17, 91, -1, "Greenhouse Roof", 1);// 169
			AddComplexComponent( (BaseAddon) this, 1535, -5, -2, 17, 91, -1, "Greenhouse Roof", 1);// 170
			AddComplexComponent( (BaseAddon) this, 1535, -5, -1, 17, 91, -1, "Greenhouse Roof", 1);// 171
			AddComplexComponent( (BaseAddon) this, 1535, -5, 0, 17, 91, -1, "Greenhouse Roof", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1535, -5, 1, 17, 91, -1, "Greenhouse Roof", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1535, -5, 2, 17, 91, -1, "Greenhouse Roof", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1535, -5, 3, 17, 91, -1, "Greenhouse Roof", 1);// 175
			AddComplexComponent( (BaseAddon) this, 1535, -5, -4, 17, 91, -1, "Greenhouse Roof", 1);// 176
			AddComplexComponent( (BaseAddon) this, 1535, -4, -5, 20, 91, -1, "Greenhouse Roof", 1);// 177
			AddComplexComponent( (BaseAddon) this, 1535, -4, -4, 20, 91, -1, "Greenhouse Roof", 1);// 178
			AddComplexComponent( (BaseAddon) this, 1535, -4, -3, 20, 91, -1, "Greenhouse Roof", 1);// 179
			AddComplexComponent( (BaseAddon) this, 1535, -4, -2, 20, 91, -1, "Greenhouse Roof", 1);// 180
			AddComplexComponent( (BaseAddon) this, 1535, -4, -1, 20, 91, -1, "Greenhouse Roof", 1);// 181
			AddComplexComponent( (BaseAddon) this, 1535, -4, 0, 20, 91, -1, "Greenhouse Roof", 1);// 182
			AddComplexComponent( (BaseAddon) this, 1535, -4, 1, 20, 91, -1, "Greenhouse Roof", 1);// 183
			AddComplexComponent( (BaseAddon) this, 1535, -4, 2, 20, 91, -1, "Greenhouse Roof", 1);// 184
			AddComplexComponent( (BaseAddon) this, 1535, -4, 3, 20, 91, -1, "Greenhouse Roof", 1);// 185
			AddComplexComponent( (BaseAddon) this, 1535, -3, -5, 23, 91, -1, "Greenhouse Roof", 1);// 186
			AddComplexComponent( (BaseAddon) this, 1535, -3, -4, 23, 91, -1, "Greenhouse Roof", 1);// 187
			AddComplexComponent( (BaseAddon) this, 1535, -3, -3, 23, 91, -1, "Greenhouse Roof", 1);// 188
			AddComplexComponent( (BaseAddon) this, 1535, -3, -2, 23, 91, -1, "Greenhouse Roof", 1);// 189
			AddComplexComponent( (BaseAddon) this, 1535, -3, -1, 23, 91, -1, "Greenhouse Roof", 1);// 190
			AddComplexComponent( (BaseAddon) this, 1535, -3, 0, 23, 91, -1, "Greenhouse Roof", 1);// 191
			AddComplexComponent( (BaseAddon) this, 1535, -3, 1, 23, 91, -1, "Greenhouse Roof", 1);// 192
			AddComplexComponent( (BaseAddon) this, 1535, -3, 2, 23, 91, -1, "Greenhouse Roof", 1);// 193
			AddComplexComponent( (BaseAddon) this, 1535, -3, 3, 23, 91, -1, "Greenhouse Roof", 1);// 194
			AddComplexComponent( (BaseAddon) this, 1535, -2, -5, 26, 91, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 1535, -2, -4, 26, 91, -1, "Greenhouse Roof", 1);// 196
			AddComplexComponent( (BaseAddon) this, 1535, -2, -3, 26, 91, -1, "Greenhouse Roof", 1);// 197
			AddComplexComponent( (BaseAddon) this, 1535, -2, -2, 26, 91, -1, "Greenhouse Roof", 1);// 198
			AddComplexComponent( (BaseAddon) this, 1535, -2, -1, 26, 91, -1, "Greenhouse Roof", 1);// 199
			AddComplexComponent( (BaseAddon) this, 1535, -2, 0, 26, 91, -1, "Greenhouse Roof", 1);// 200
			AddComplexComponent( (BaseAddon) this, 1535, -2, 1, 26, 91, -1, "Greenhouse Roof", 1);// 201
			AddComplexComponent( (BaseAddon) this, 1535, -2, 2, 26, 91, -1, "Greenhouse Roof", 1);// 202
			AddComplexComponent( (BaseAddon) this, 1535, -2, 3, 26, 91, -1, "Greenhouse Roof", 1);// 203
			AddComplexComponent( (BaseAddon) this, 1538, 5, -5, 20, 91, -1, "Greenhouse Roof", 1);// 204
			AddComplexComponent( (BaseAddon) this, 1538, 5, -4, 20, 91, -1, "Greenhouse Roof", 1);// 205
			AddComplexComponent( (BaseAddon) this, 1538, 5, -3, 20, 91, -1, "Greenhouse Roof", 1);// 206
			AddComplexComponent( (BaseAddon) this, 1538, 5, -2, 20, 91, -1, "Greenhouse Roof", 1);// 207
			AddComplexComponent( (BaseAddon) this, 1538, 5, -1, 20, 91, -1, "Greenhouse Roof", 1);// 208
			AddComplexComponent( (BaseAddon) this, 1538, 5, 0, 20, 91, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 1538, 5, 1, 20, 91, -1, "Greenhouse Roof", 1);// 210
			AddComplexComponent( (BaseAddon) this, 1538, 5, 2, 20, 91, -1, "Greenhouse Roof", 1);// 211
			AddComplexComponent( (BaseAddon) this, 1538, 5, 3, 20, 91, -1, "Greenhouse Roof", 1);// 212
			AddComplexComponent( (BaseAddon) this, 1538, 4, -5, 23, 91, -1, "Greenhouse Roof", 1);// 213
			AddComplexComponent( (BaseAddon) this, 1538, 4, -4, 23, 91, -1, "Greenhouse Roof", 1);// 214
			AddComplexComponent( (BaseAddon) this, 1538, 4, -3, 23, 91, -1, "Greenhouse Roof", 1);// 215
			AddComplexComponent( (BaseAddon) this, 1538, 4, -2, 23, 91, -1, "Greenhouse Roof", 1);// 216
			AddComplexComponent( (BaseAddon) this, 1538, 4, -1, 23, 91, -1, "Greenhouse Roof", 1);// 217
			AddComplexComponent( (BaseAddon) this, 1538, 4, 0, 23, 91, -1, "Greenhouse Roof", 1);// 218
			AddComplexComponent( (BaseAddon) this, 1538, 4, 1, 23, 91, -1, "Greenhouse Roof", 1);// 219
			AddComplexComponent( (BaseAddon) this, 1538, 4, 2, 23, 91, -1, "Greenhouse Roof", 1);// 220
			AddComplexComponent( (BaseAddon) this, 1538, 4, 3, 23, 91, -1, "Greenhouse Roof", 1);// 221
			AddComplexComponent( (BaseAddon) this, 1538, 3, -5, 26, 91, -1, "Greenhouse Roof", 1);// 222
			AddComplexComponent( (BaseAddon) this, 1538, 3, -4, 26, 91, -1, "Greenhouse Roof", 1);// 223
			AddComplexComponent( (BaseAddon) this, 1538, 3, -3, 26, 91, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 1538, 3, -2, 26, 91, -1, "Greenhouse Roof", 1);// 225
			AddComplexComponent( (BaseAddon) this, 1538, 3, -1, 26, 91, -1, "Greenhouse Roof", 1);// 226
			AddComplexComponent( (BaseAddon) this, 1538, 3, 0, 26, 91, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 1538, 3, 1, 26, 91, -1, "Greenhouse Roof", 1);// 228
			AddComplexComponent( (BaseAddon) this, 1538, 3, 2, 26, 91, -1, "Greenhouse Roof", 1);// 229
			AddComplexComponent( (BaseAddon) this, 1538, 3, 3, 26, 91, -1, "Greenhouse Roof", 1);// 230
			AddComplexComponent( (BaseAddon) this, 1538, 2, -5, 29, 91, -1, "Greenhouse Roof", 1);// 231
			AddComplexComponent( (BaseAddon) this, 1538, 2, -4, 29, 91, -1, "Greenhouse Roof", 1);// 232
			AddComplexComponent( (BaseAddon) this, 1538, 2, -3, 29, 91, -1, "Greenhouse Roof", 1);// 233
			AddComplexComponent( (BaseAddon) this, 1538, 2, -2, 29, 91, -1, "Greenhouse Roof", 1);// 234
			AddComplexComponent( (BaseAddon) this, 1538, 2, -1, 29, 91, -1, "Greenhouse Roof", 1);// 235
			AddComplexComponent( (BaseAddon) this, 1538, 2, 0, 29, 91, -1, "Greenhouse Roof", 1);// 236
			AddComplexComponent( (BaseAddon) this, 1538, 2, 1, 29, 91, -1, "", 1);// 237
			AddComplexComponent( (BaseAddon) this, 1538, 2, 2, 29, 91, -1, "Greenhouse Roof", 1);// 238
			AddComplexComponent( (BaseAddon) this, 1538, 2, 3, 29, 91, -1, "Greenhouse Roof", 1);// 239
			AddComplexComponent( (BaseAddon) this, 1535, -1, -5, 29, 91, -1, "Greenhouse Roof", 1);// 240
			AddComplexComponent( (BaseAddon) this, 1535, -1, -4, 29, 91, -1, "Greenhouse Roof", 1);// 241
			AddComplexComponent( (BaseAddon) this, 1535, -1, -3, 29, 91, -1, "Greenhouse Roof", 1);// 242
			AddComplexComponent( (BaseAddon) this, 1535, -1, -2, 29, 91, -1, "Greenhouse Roof", 1);// 243
			AddComplexComponent( (BaseAddon) this, 1535, -1, -1, 29, 91, -1, "Greenhouse Roof", 1);// 244
			AddComplexComponent( (BaseAddon) this, 1535, -1, 0, 29, 91, -1, "Greenhouse Roof", 1);// 245
			AddComplexComponent( (BaseAddon) this, 1535, -1, 1, 29, 91, -1, "Greenhouse Roof", 1);// 246
			AddComplexComponent( (BaseAddon) this, 1535, -1, 2, 29, 91, -1, "Greenhouse Roof", 1);// 247
			AddComplexComponent( (BaseAddon) this, 1535, -1, 3, 29, 91, -1, "Greenhouse Roof", 1);// 248
			AddComplexComponent( (BaseAddon) this, 1535, 0, -5, 32, 91, -1, "Greenhouse Roof", 1);// 249
			AddComplexComponent( (BaseAddon) this, 1535, 0, -4, 32, 91, -1, "Greenhouse Roof", 1);// 250
			AddComplexComponent( (BaseAddon) this, 1535, 0, -3, 32, 91, -1, "Greenhouse Roof", 1);// 251
			AddComplexComponent( (BaseAddon) this, 1535, 0, -2, 32, 91, -1, "Greenhouse Roof", 1);// 252
			AddComplexComponent( (BaseAddon) this, 1535, 0, -1, 32, 91, -1, "Greenhouse Roof", 1);// 253
			AddComplexComponent( (BaseAddon) this, 1535, 0, 0, 32, 91, -1, "Greenhouse Roof", 1);// 254
			AddComplexComponent( (BaseAddon) this, 1535, 0, 1, 32, 91, -1, "Greenhouse Roof", 1);// 255
			AddComplexComponent( (BaseAddon) this, 1535, 0, 2, 32, 91, -1, "Greenhouse Roof", 1);// 256
			AddComplexComponent( (BaseAddon) this, 1535, 0, 3, 32, 91, -1, "Greenhouse Roof", 1);// 257
			AddComplexComponent( (BaseAddon) this, 1587, 1, -5, 32, 91, -1, "Greenhouse Roof", 1);// 258
			AddComplexComponent( (BaseAddon) this, 1587, 1, -4, 32, 91, -1, "Greenhouse Roof", 1);// 259
			AddComplexComponent( (BaseAddon) this, 1587, 1, -3, 32, 91, -1, "Greenhouse Roof", 1);// 260
			AddComplexComponent( (BaseAddon) this, 1587, 1, -2, 32, 91, -1, "", 1);// 261
			AddComplexComponent( (BaseAddon) this, 1587, 1, -1, 32, 91, -1, "Greenhouse Roof", 1);// 262
			AddComplexComponent( (BaseAddon) this, 1587, 1, 0, 32, 91, -1, "Greenhouse Roof", 1);// 263
			AddComplexComponent( (BaseAddon) this, 1587, 1, 1, 32, 91, -1, "Greenhouse Roof", 1);// 264
			AddComplexComponent( (BaseAddon) this, 1587, 1, 2, 32, 91, -1, "Greenhouse Roof", 1);// 265
			AddComplexComponent( (BaseAddon) this, 1587, 1, 3, 32, 91, -1, "Greenhouse Roof", 1);// 266
			AddComplexComponent( (BaseAddon) this, 10384, -5, 4, 5, 91, -1, "", 1);// 289
			AddComplexComponent( (BaseAddon) this, 10384, -5, 5, 5, 91, -1, "", 1);// 290
			AddComplexComponent( (BaseAddon) this, 10384, 5, 4, 5, 91, -1, "", 1);// 291
			AddComplexComponent( (BaseAddon) this, 10384, 5, 5, 5, 91, -1, "", 1);// 292
			AddComplexComponent( (BaseAddon) this, 10387, -4, 5, 5, 91, -1, "", 1);// 293
			AddComplexComponent( (BaseAddon) this, 10387, -3, 5, 5, 91, -1, "", 1);// 294
			AddComplexComponent( (BaseAddon) this, 10387, -2, 5, 5, 91, -1, "", 1);// 295
			AddComplexComponent( (BaseAddon) this, 10387, -1, 5, 5, 91, -1, "", 1);// 296
			AddComplexComponent( (BaseAddon) this, 10387, 2, 5, 5, 91, -1, "", 1);// 297
			AddComplexComponent( (BaseAddon) this, 10387, 3, 5, 5, 91, -1, "", 1);// 298
			AddComplexComponent( (BaseAddon) this, 10387, 4, 5, 5, 91, -1, "", 1);// 299
			AddComplexComponent( (BaseAddon) this, 10387, 5, 5, 5, 91, -1, "", 1);// 300
			AddComplexComponent( (BaseAddon) this, 1535, -4, 4, 20, 91, -1, "Greenhouse Roof", 1);// 301
			AddComplexComponent( (BaseAddon) this, 1535, -4, 5, 20, 91, -1, "Greenhouse Roof", 1);// 302
			AddComplexComponent( (BaseAddon) this, 1535, -4, 6, 20, 91, -1, "Greenhouse Roof", 1);// 303
			AddComplexComponent( (BaseAddon) this, 1535, -3, 4, 23, 91, -1, "Greenhouse Roof", 1);// 304
			AddComplexComponent( (BaseAddon) this, 1535, -3, 5, 23, 91, -1, "Greenhouse Roof", 1);// 305
			AddComplexComponent( (BaseAddon) this, 1535, -3, 6, 23, 91, -1, "Greenhouse Roof", 1);// 306
			AddComplexComponent( (BaseAddon) this, 1535, -2, 4, 26, 91, -1, "Greenhouse Roof", 1);// 307
			AddComplexComponent( (BaseAddon) this, 1535, -2, 5, 26, 91, -1, "Greenhouse Roof", 1);// 308
			AddComplexComponent( (BaseAddon) this, 1535, -2, 6, 26, 91, -1, "Greenhouse Roof", 1);// 309
			AddComplexComponent( (BaseAddon) this, 1538, 5, 4, 20, 91, -1, "", 1);// 310
			AddComplexComponent( (BaseAddon) this, 1538, 5, 5, 20, 91, -1, "Greenhouse Roof", 1);// 311
			AddComplexComponent( (BaseAddon) this, 1538, 5, 6, 20, 91, -1, "Greenhouse Roof", 1);// 312
			AddComplexComponent( (BaseAddon) this, 1538, 4, 4, 23, 91, -1, "Greenhouse Roof", 1);// 313
			AddComplexComponent( (BaseAddon) this, 1538, 4, 5, 23, 91, -1, "Greenhouse Roof", 1);// 314
			AddComplexComponent( (BaseAddon) this, 1538, 4, 6, 23, 91, -1, "Greenhouse Roof", 1);// 315
			AddComplexComponent( (BaseAddon) this, 1538, 3, 4, 26, 91, -1, "Greenhouse Roof", 1);// 316
			AddComplexComponent( (BaseAddon) this, 1538, 3, 5, 26, 91, -1, "Greenhouse Roof", 1);// 317
			AddComplexComponent( (BaseAddon) this, 1538, 3, 6, 26, 91, -1, "Greenhouse Roof", 1);// 318
			AddComplexComponent( (BaseAddon) this, 1538, 2, 4, 29, 91, -1, "", 1);// 319
			AddComplexComponent( (BaseAddon) this, 1538, 2, 5, 29, 91, -1, "Greenhouse Roof", 1);// 320
			AddComplexComponent( (BaseAddon) this, 1538, 2, 6, 29, 91, -1, "Greenhouse Roof", 1);// 321
			AddComplexComponent( (BaseAddon) this, 1535, -1, 4, 29, 91, -1, "Greenhouse Roof", 1);// 322
			AddComplexComponent( (BaseAddon) this, 1535, -1, 5, 29, 91, -1, "Greenhouse Roof", 1);// 323
			AddComplexComponent( (BaseAddon) this, 1535, -1, 6, 29, 91, -1, "Greenhouse Roof", 1);// 324
			AddComplexComponent( (BaseAddon) this, 1535, 0, 4, 32, 91, -1, "Greenhouse Roof", 1);// 325
			AddComplexComponent( (BaseAddon) this, 1535, 0, 5, 32, 91, -1, "Greenhouse Roof", 1);// 326
			AddComplexComponent( (BaseAddon) this, 1535, 0, 6, 32, 91, -1, "Greenhouse Roof", 1);// 327
			AddComplexComponent( (BaseAddon) this, 1587, 1, 4, 32, 91, -1, "", 1);// 328
			AddComplexComponent( (BaseAddon) this, 1587, 1, 5, 32, 91, -1, "Greenhouse Roof", 1);// 329
			AddComplexComponent( (BaseAddon) this, 1587, 1, 6, 32, 91, -1, "Greenhouse Roof", 1);// 330
			AddComplexComponent( (BaseAddon) this, 1535, -5, 4, 17, 91, -1, "Greenhouse Roof", 1);// 331
			AddComplexComponent( (BaseAddon) this, 1535, -5, 5, 17, 91, -1, "Greenhouse Roof", 1);// 332
			AddComplexComponent( (BaseAddon) this, 1535, -5, 6, 17, 91, -1, "Greenhouse Roof", 1);// 333

		}

		public GreenhouseEmptyAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GreenhouseEmptyAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GreenhouseEmptyAddon();
			}
		}

		[Constructable]
		public GreenhouseEmptyAddonDeed()
		{
			Name = "GreenhouseEmpty";
		}

		public GreenhouseEmptyAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}