
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TikiBarAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {10080, -4, -4, 0}, {10080, -3, -4, 0}, {10080, -2, -4, 0}// 1	2	3	
			, {10080, -1, -4, 0}, {10080, 0, -4, 0}, {10076, -4, -4, 5}// 4	5	6	
			, {9269, -3, -3, 5}, {9269, -3, -2, 5}, {9269, -3, -1, 5}// 7	8	9	
			, {9269, -3, 0, 5}, {9269, -3, 1, 5}, {9269, -3, 2, 5}// 10	11	12	
			, {9269, -2, -3, 5}, {9269, -2, -2, 5}, {9269, -2, -1, 5}// 13	14	15	
			, {9269, -2, 0, 5}, {9269, -2, 1, 5}, {9269, -2, 2, 5}// 16	17	18	
			, {9269, -1, -3, 5}, {9269, -1, -2, 5}, {9269, -1, -1, 5}// 19	20	21	
			, {9269, -1, 0, 5}, {9269, -1, 1, 5}, {9269, -1, 2, 5}// 22	23	24	
			, {9269, 0, -3, 5}, {9269, 0, -2, 5}, {9269, 0, -1, 5}// 25	26	27	
			, {9269, 0, 0, 5}, {9269, 0, 1, 5}, {9269, 0, 2, 5}// 28	29	30	
			, {4099, -2, 2, 5}, {1849, -1, 3, 0}, {1849, 0, 3, 0}// 31	32	33	
			, {10078, -4, 2, 5}, {10078, -4, 1, 5}, {10078, -4, 0, 5}// 34	35	36	
			, {10078, -4, -1, 5}, {10078, -4, -2, 5}, {10078, -4, -3, 5}// 37	38	39	
			, {10080, -3, 2, 0}, {10080, -2, 2, 0}, {10076, -4, 2, 5}// 40	41	42	
			, {6427, -3, -3, 5}, {6426, -2, -3, 5}, {6426, -1, -3, 5}// 43	44	45	
			, {6417, 0, -3, 5}, {6419, 0, -1, 5}, {6428, 0, -2, 5}// 46	47	48	
			, {6430, -1, -1, 5}, {6431, -2, -1, 5}, {2602, -2, 0, 5}// 49	50	51	
			, {2602, -1, 0, 5}, {2602, 0, 0, 5}, {2463, -2, -1, 13}// 52	53	54	
			, {2503, -1, -1, 13}, {8063, 0, -1, 13}, {8077, 0, -2, 13}// 55	56	57	
			, {2462, -1, -3, 14}, {6870, -3, -3, 15}, {6870, -2, -3, 15}// 58	59	60	
			, {1425, -3, -3, 25}, {1425, -3, -1, 25}, {1425, -3, 0, 25}// 61	62	63	
			, {1425, -3, 1, 25}, {1425, -3, 2, 25}, {1425, -3, 3, 25}// 64	65	66	
			, {1425, -3, -2, 25}, {1425, -2, -3, 28}, {1425, -2, -2, 28}// 67	68	69	
			, {1425, -2, -1, 28}, {1425, -2, 0, 28}, {1425, -2, 1, 28}// 70	71	72	
			, {1425, -2, 2, 28}, {1425, -2, 3, 28}, {1425, -1, -3, 31}// 73	74	75	
			, {1425, -1, -2, 31}, {1425, -1, -1, 31}, {1425, -1, 0, 31}// 76	77	78	
			, {1425, -1, 1, 31}, {1425, -1, 2, 31}, {1425, -1, 3, 31}// 79	80	81	
			, {1423, 0, 1, 31}, {1423, 0, 2, 31}, {1423, 0, 3, 31}// 82	83	84	
			, {1423, 0, -3, 31}, {1423, 0, -2, 31}, {1423, 0, -1, 31}// 85	86	87	
			, {1423, 0, 0, 31}, {3222, -4, 4, 0}, {3231, -3, 3, 0}// 88	89	90	
			, {6811, -2, 3, 0}, {10080, 1, -4, 0}, {10080, 2, -4, 0}// 91	93	94	
			, {10076, 2, -4, 5}, {10067, 2, 2, 0}, {9269, 1, -3, 5}// 95	96	97	
			, {9269, 1, -2, 5}, {9269, 1, -1, 5}, {9269, 1, 0, 5}// 98	99	100	
			, {9269, 1, 1, 5}, {9269, 1, 2, 5}, {9269, 2, -3, 5}// 101	102	103	
			, {9269, 2, -2, 5}, {9269, 2, -1, 5}, {9269, 2, 0, 5}// 104	105	106	
			, {9269, 2, 1, 5}, {9269, 2, 2, 5}, {1849, 1, 3, 0}// 107	108	109	
			, {1850, 3, -1, 0}, {1850, 3, 0, 0}, {1850, 3, 1, 0}// 110	111	112	
			, {10077, 2, -2, 0}, {10077, 2, -3, 0}, {10076, 2, 2, 5}// 113	114	115	
			, {2602, 1, -2, 5}, {2602, 1, -1, 5}, {1417, 3, 3, 25}// 116	117	118	
			, {1415, 3, -3, 25}, {1415, 2, -2, 28}, {1415, 1, -1, 31}// 119	120	121	
			, {1417, 2, 2, 28}, {1417, 1, 1, 31}, {8581, 3, 1, 31}// 122	123	124	
			, {8581, 2, 1, 31}, {8581, 3, 2, 28}, {8582, 1, 0, 31}// 125	126	127	
			, {8582, 2, -1, 29}, {8582, 2, 0, 31}, {8582, 3, -2, 28}// 128	129	130	
			, {8582, 3, -1, 28}, {8582, 3, 0, 31}, {8577, 1, 2, 31}// 131	132	133	
			, {8577, 1, 3, 28}, {8577, 2, 3, 25}, {8577, 1, -2, 31}// 134	135	136	
			, {8577, 1, -3, 28}, {8577, 2, -3, 26}, {3223, 2, 3, 0}// 137	138	139	
			, {3223, 3, 3, 0}, {3223, 3, 2, 0}, {3231, 3, -3, 0}// 140	141	142	
			, {6811, 3, -2, 0}// 143	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TikiBarAddonDeed();
			}
		}

		[ Constructable ]
		public TikiBarAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2578, -2, 4, 0, 0, 29, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 2578, 2, 4, 0, 0, 29, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 2578, 4, 2, 0, 0, 29, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 2578, 4, -2, 0, 0, 29, "", 1);// 146

		}

		public TikiBarAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TikiBarAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TikiBarAddon();
			}
		}

		[Constructable]
		public TikiBarAddonDeed()
		{
			Name = "TikiBar";
		}

		public TikiBarAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}